-- Auto-generated demo seed export (INSERT OR IGNORE)
PRAGMA foreign_keys = OFF;

-- distributors
INSERT OR IGNORE INTO distributors (id, name, region, phone, deleted_at, created_at, updated_at) VALUES ('dist-nagpur-01', 'Vikram Mehta', 'Maharashtra Central', '+91 98230 44120', NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO distributors (id, name, region, phone, deleted_at, created_at, updated_at) VALUES ('dist-pune-02', 'Sanjay Pawar', 'Western Maharashtra', '+91 98220 88990', NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO distributors (id, name, region, phone, deleted_at, created_at, updated_at) VALUES ('dist-hyd-03', 'Lakshmi Rao', 'South India', '+91 98490 11223', NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');

-- dealers
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-sharma', 'dist-nagpur-01', 'user-sales-exec', 'BR-NGP-014', 'Sharma Furnishings', NULL, 'Sitabuldi, Nagpur', 'Shop 14, Sitabuldi Main Road, Nagpur, Maharashtra 440001', '+91 98765 43210', 'rajesh@sharmafurnishings.in', NULL, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-patil', 'dist-nagpur-01', 'user-sales-exec', 'BR-NGP-022', 'Patil Mattress Gallery', NULL, 'Dharampeth, Nagpur', '45, Dharampeth Extension, Near Law College, Nagpur 440010', '+91 97654 22108', 'contact@patilgallery.com', NULL, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-kulkarni', 'dist-pune-02', NULL, 'BR-PUN-008', 'Kulkarni Sleep Studio', NULL, 'FC Road, Pune', '102, FC Road, Shivajinagar, Pune, Maharashtra 411004', '+91 98901 33445', 'studio@kulkarnisleep.in', NULL, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-reddy', 'dist-hyd-03', NULL, 'BR-HYD-031', 'Reddy Home Comfort', NULL, 'Banjara Hills, Hyderabad', NULL, '+91 98480 55667', 'orders@reddycomfort.com', NULL, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-menon', NULL, NULL, 'BR-COK-005', 'Menon Bedding House', NULL, 'MG Road, Kochi', NULL, '+91 98470 11223', 'sales@menonbedding.in', NULL, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-gupta', 'dist-pune-02', NULL, 'BR-IND-019', 'Gupta Mattress Mart', NULL, 'Vijay Nagar, Indore', NULL, '+91 98260 77889', 'gupta.mart@gmail.com', NULL, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-singh', 'dist-nagpur-01', NULL, 'BR-BPL-012', 'Singh Sleep Solutions', NULL, 'MP Nagar, Bhopal', NULL, '+91 94250 66771', 'info@singhsleep.in', NULL, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-desai', 'dist-pune-02', NULL, 'BR-AHD-027', 'Desai Furnishing World', NULL, 'Navrangpura, Ahmedabad', NULL, '+91 98790 44556', 'desai@furnishingworld.co.in', NULL, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-iyer', 'dist-nagpur-01', NULL, 'BR-CBE-003', 'Iyer Comfort Zone', NULL, 'RS Puram, Coimbatore', NULL, '+91 98422 88990', 'iyerzone@gmail.com', NULL, 0, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealers (id, distributor_id, sales_executive_user_id, code, store_name, contact_name, location, address, phone, email, gst_number, active, deleted_at, created_at, updated_at) VALUES ('dlr-chavan', 'dist-nagpur-01', NULL, 'BR-NAS-016', 'Chavan Home Décor', NULL, 'College Road, Nashik', NULL, '+91 98220 33441', 'chavan@homedecor.in', NULL, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');

-- users
INSERT OR IGNORE INTO users (id, phone, name, email, role, dealer_id, distributor_id, status, deleted_at, created_at, updated_at) VALUES ('user-dist-vikram', '+919823044120', 'Vikram Mehta', NULL, 'distributor', NULL, 'dist-nagpur-01', 'active', NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO users (id, phone, name, email, role, dealer_id, distributor_id, status, deleted_at, created_at, updated_at) VALUES ('user-admin', '+919999999999', 'BackRest Admin', NULL, 'master_admin', NULL, NULL, 'active', NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO users (id, phone, name, email, role, dealer_id, distributor_id, status, deleted_at, created_at, updated_at) VALUES ('user-admin-staff', '+919888877777', 'Priya Operations', NULL, 'admin_staff', NULL, NULL, 'active', NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO users (id, phone, name, email, role, dealer_id, distributor_id, status, deleted_at, created_at, updated_at) VALUES ('user-sales-exec', '+919777766666', 'Amit Sales', NULL, 'sales_executive', NULL, NULL, 'active', NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO users (id, phone, name, email, role, dealer_id, distributor_id, status, deleted_at, created_at, updated_at) VALUES ('user-dealer-sharma', '+919876543210', 'Rajesh Sharma', NULL, 'dealer', 'dlr-sharma', NULL, 'active', NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO users (id, phone, name, email, role, dealer_id, distributor_id, status, deleted_at, created_at, updated_at) VALUES ('user-57e06c72', '+919296431152', 'Test Dealer', NULL, 'dealer', NULL, NULL, 'pending_approval', NULL, '2026-08-21T07:13:51.158Z', '2026-08-21T07:13:51.158Z');
INSERT OR IGNORE INTO users (id, phone, name, email, role, dealer_id, distributor_id, status, deleted_at, created_at, updated_at) VALUES ('user-7d01f796', '+919296494614', 'Test Dealer', NULL, 'dealer', NULL, NULL, 'pending_approval', NULL, '2026-08-21T07:14:54.617Z', '2026-08-21T07:14:54.617Z');

-- dealer_assignments
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-sharma-dist', 'dlr-sharma', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-patil-dist', 'dlr-patil', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-kulkarni-dist', 'dlr-kulkarni', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-reddy-dist', 'dlr-reddy', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-menon-dist', 'dlr-menon', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-gupta-dist', 'dlr-gupta', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-singh-dist', 'dlr-singh', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-desai-dist', 'dlr-desai', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-iyer-dist', 'dlr-iyer', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-chavan-dist', 'dlr-chavan', 'user-dist-vikram', 'distributor', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-sharma-se', 'dlr-sharma', 'user-sales-exec', 'sales_executive', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO dealer_assignments (id, dealer_id, assignee_user_id, assignee_role, created_at) VALUES ('asgn-dlr-patil-se', 'dlr-patil', 'user-sales-exec', 'sales_executive', '2026-08-21 05:27:45');

-- products
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('eco-bond', 'Eco Bond', 'Mattresses', '3 Years', NULL, 'Everyday value bonded foam mattress.', NULL, '/products/mattress-premium.jpg', 1, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('twin', 'Twin', 'Mattresses', '5 Years', NULL, 'Balanced comfort for daily sleep.', NULL, '/products/mattress-premium.jpg', 2, 1, NULL, '2026-08-21 05:27:45', '2026-08-21 05:27:45');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('twin-plush', 'Twin Plush', 'Mattresses', '5 Years', NULL, 'Softer top feel with firm base.', NULL, '/products/mattress-premium.jpg', 3, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('twin-max', 'Twin Max', 'Mattresses', '5 Years', NULL, 'Extra support for heavier use.', NULL, '/products/mattress-premium.jpg', 4, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('aquafresh', 'AquaFresh', 'Mattresses', '7 Years', NULL, 'Breathable cool-sleep foam.', NULL, '/products/mattress-premium.jpg', 5, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('aquafresh-plush', 'AquaFresh Plush', 'Mattresses', '7 Years', NULL, 'Plush surface, cool and airy.', NULL, '/products/mattress-premium.jpg', 6, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('aquafresh-serene', 'AquaFresh Serene', 'Mattresses', '7 Years', NULL, 'Quiet, calm, pressure-free sleep.', NULL, '/products/mattress-premium.jpg', 7, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('aquafresh-bounce', 'AquaFresh Bounce', 'Mattresses', '7 Years', NULL, 'Springy feel with quick recovery.', NULL, '/products/mattress-premium.jpg', 8, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('delight', 'Delight', 'Mattresses', '10 Years', NULL, 'Premium comfort for long life.', NULL, '/products/mattress-premium.jpg', 9, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('delight-max', 'Delight Max', 'Mattresses', '10 Years', NULL, 'Slim profile, maximum support.', NULL, '/products/mattress-premium.jpg', 10, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('delight-cool', 'Delight Cool', 'Mattresses', '10 Years', NULL, 'Cool gel layer for hot nights.', NULL, '/products/mattress-premium.jpg', 11, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('latexo', 'Latexo', 'Mattresses', '10 Years', NULL, 'Natural latex bounce and breathability.', NULL, '/products/mattress-premium.jpg', 12, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('latexo-plush', 'Latexo Plush', 'Mattresses', '10 Years', NULL, 'Soft latex top with firm core.', NULL, '/products/mattress-premium.jpg', 13, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('orthomatic', 'Orthomatic', 'Mattresses', '12 Years', NULL, 'Orthopaedic support for back comfort.', NULL, '/products/mattress-premium.jpg', 14, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('posturematic', 'Posturematic', 'Mattresses', '12 Years', NULL, 'Posture-aligned zoned support.', NULL, '/products/mattress-premium.jpg', 15, 1, NULL, '2026-08-21 05:27:46', '2026-08-21 05:27:46');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('theramatic', 'Theramatic', 'Mattresses', '12 Years', NULL, 'Therapeutic relief for pressure points.', NULL, '/products/mattress-premium.jpg', 16, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('magnamatic', 'Magnamatic', 'Mattresses', '12 Years', NULL, 'Magnetic therapy comfort layer.', NULL, '/products/mattress-premium.jpg', 17, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('spacematic', 'Spacematic', 'Mattresses', '12 Years', NULL, 'Top of the range luxury sleep.', NULL, '/products/mattress-premium.jpg', 18, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('2-fold-mattress', '2 Fold Mattress', 'Foldable', '3 Years', '36 × 72', 'Folds in two — easy to store and carry.', NULL, '/products/cushion-support.jpg', 19, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('3-fold-mattress', '3 Fold Mattress', 'Foldable', '3 Years', '36 × 72', 'Folds in three — perfect for guests.', NULL, '/products/cushion-support.jpg', 20, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('pillow-memory-king', 'Memory King', 'Pillows', '3 Years', '17 × 27', '17 × 27 pillow', NULL, '/products/pillow-memory.jpg', 21, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('pillow-memory-queen', 'Memory Queen', 'Pillows', '3 Years', '16 × 24', '16 × 24 pillow', NULL, '/products/pillow-memory.jpg', 22, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('pillow-contour-king', 'Contour King', 'Pillows', '3 Years', '17 × 27', '17 × 27 pillow', NULL, '/products/pillow-memory.jpg', 23, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('pillow-latex', 'Latex', 'Pillows', '3 Years', '17 × 27', '17 × 27 pillow', NULL, '/products/pillow-memory.jpg', 24, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('pillow-fiber', 'Fiber', 'Pillows', '3 Years', '16 × 24', '16 × 24 pillow', NULL, '/products/pillow-memory.jpg', 25, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('pillow-wedge-king', 'Wedge King', 'Pillows', '3 Years', '24 × 24 × 10', '24 × 24 × 10 pillow', NULL, '/products/pillow-memory.jpg', 26, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');
INSERT OR IGNORE INTO products (id, name, category, guarantee, fixed_size, blurb, image_r2_key, image_url, sort_order, active, deleted_at, created_at, updated_at) VALUES ('pillow-wedge-queen', 'Wedge Queen', 'Pillows', '3 Years', '18 × 20 × 9', '18 × 20 × 9 pillow', NULL, '/products/pillow-memory.jpg', 27, 1, NULL, '2026-08-21 05:27:47', '2026-08-21 05:27:47');

-- product_thicknesses
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (1, 'eco-bond', '4"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (2, 'twin', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (3, 'twin', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (4, 'twin', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (5, 'twin-plush', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (6, 'twin-plush', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (7, 'twin-plush', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (8, 'twin-max', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (9, 'twin-max', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (10, 'twin-max', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (11, 'aquafresh', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (12, 'aquafresh', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (13, 'aquafresh', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (14, 'aquafresh-plush', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (15, 'aquafresh-plush', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (16, 'aquafresh-plush', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (17, 'aquafresh-serene', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (18, 'aquafresh-serene', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (19, 'aquafresh-serene', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (20, 'aquafresh-bounce', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (21, 'aquafresh-bounce', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (22, 'aquafresh-bounce', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (23, 'delight', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (24, 'delight', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (25, 'delight', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (26, 'delight-max', '4"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (27, 'delight-cool', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (28, 'delight-cool', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (29, 'delight-cool', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (30, 'latexo', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (31, 'latexo', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (32, 'latexo', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (33, 'latexo-plush', '5"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (34, 'latexo-plush', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (35, 'latexo-plush', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (36, 'orthomatic', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (37, 'orthomatic', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (38, 'orthomatic', '10"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (39, 'posturematic', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (40, 'posturematic', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (41, 'posturematic', '10"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (42, 'theramatic', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (43, 'theramatic', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (44, 'theramatic', '10"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (45, 'magnamatic', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (46, 'magnamatic', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (47, 'magnamatic', '10"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (48, 'spacematic', '6"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (49, 'spacematic', '8"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (50, 'spacematic', '10"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (51, '2-fold-mattress', '2"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (52, '2-fold-mattress', '3"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (53, '3-fold-mattress', '2"', 0);
INSERT OR IGNORE INTO product_thicknesses (id, product_id, thickness, sort_order) VALUES (54, '3-fold-mattress', '3"', 0);

-- product_prices
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (1, 'eco-bond', 5200, 3400, 24, '2 × Fiber Pillows', '2026-08-21 05:27:45', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (2, 'twin', 7900, 5300, 36, '2 × Fiber Pillows', '2026-08-21 05:27:45', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (3, 'twin-plush', 8600, 5800, 40, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (4, 'twin-max', 9400, 6300, 44, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (5, 'aquafresh', 11200, 7500, 52, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (6, 'aquafresh-plush', 12100, 8100, 56, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (7, 'aquafresh-serene', 12900, 8700, 60, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (8, 'aquafresh-bounce', 13400, 9000, 62, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (9, 'delight', 15200, 10200, 70, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (10, 'delight-max', 12400, 8300, 58, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (11, 'delight-cool', 16400, 11000, 76, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (12, 'latexo', 18600, 12500, 86, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (13, 'latexo-plush', 19900, 13400, 92, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (14, 'orthomatic', 22400, 15100, 104, '2 × Fiber Pillows', '2026-08-21 05:27:46', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (15, 'posturematic', 23600, 15900, 110, '2 × Fiber Pillows', '2026-08-21 05:27:47', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (16, 'theramatic', 24800, 16700, 116, '2 × Fiber Pillows', '2026-08-21 05:27:47', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (17, 'magnamatic', 26200, 17600, 122, '2 × Fiber Pillows', '2026-08-21 05:27:47', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (18, 'spacematic', 27800, 18700, 130, '2 × Fiber Pillows', '2026-08-21 05:27:47', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (19, '2-fold-mattress', 4200, 2800, 20, '2 × Fiber Pillows', '2026-08-21 05:27:47', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (20, '3-fold-mattress', 4600, 3100, 22, '2 × Fiber Pillows', '2026-08-21 05:27:47', NULL, 0.5, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (21, 'pillow-memory-king', 1400, 950, 8, NULL, '2026-08-21 05:27:47', NULL, 0.6, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (22, 'pillow-memory-queen', 1200, 820, 7, NULL, '2026-08-21 05:27:47', NULL, 0.6, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (23, 'pillow-contour-king', 1600, 1080, 9, NULL, '2026-08-21 05:27:47', NULL, 0.6, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (24, 'pillow-latex', 1900, 1290, 11, NULL, '2026-08-21 05:27:47', NULL, 0.6, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (25, 'pillow-fiber', 700, 460, 4, NULL, '2026-08-21 05:27:47', NULL, 0.6, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (26, 'pillow-wedge-king', 2200, 1490, 13, NULL, '2026-08-21 05:27:47', NULL, 0.6, 'dealer');
INSERT OR IGNORE INTO product_prices (id, product_id, mrp, dealer_price, points, free_items_label, effective_from, effective_to, reward_percent, reward_eligibility) VALUES (27, 'pillow-wedge-queen', 1800, 1220, 10, NULL, '2026-08-21 05:27:48', NULL, 0.6, 'dealer');

-- product_layers
INSERT OR IGNORE INTO product_layers (id, title, sort_order) VALUES ('layer-1', '3 & 5 Years Guarantee', 1);
INSERT OR IGNORE INTO product_layers (id, title, sort_order) VALUES ('layer-2', '7 Years Guarantee', 2);
INSERT OR IGNORE INTO product_layers (id, title, sort_order) VALUES ('layer-3', '10 Years Guarantee', 3);
INSERT OR IGNORE INTO product_layers (id, title, sort_order) VALUES ('layer-4', '12 Years Guarantee', 4);

-- product_layer_items
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (1, 'layer-1', 'eco-bond', '3 Years', 0);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (2, 'layer-1', 'twin', '5 Years', 1);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (3, 'layer-1', 'twin-plush', '5 Years', 2);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (4, 'layer-1', 'twin-max', '5 Years', 3);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (5, 'layer-2', 'aquafresh', NULL, 0);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (6, 'layer-2', 'aquafresh-plush', NULL, 1);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (7, 'layer-2', 'aquafresh-serene', NULL, 2);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (8, 'layer-2', 'aquafresh-bounce', NULL, 3);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (9, 'layer-3', 'delight', NULL, 0);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (10, 'layer-3', 'delight-max', NULL, 1);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (11, 'layer-3', 'delight-cool', NULL, 2);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (12, 'layer-3', 'latexo', NULL, 3);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (13, 'layer-3', 'latexo-plush', NULL, 4);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (14, 'layer-4', 'orthomatic', NULL, 0);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (15, 'layer-4', 'posturematic', NULL, 1);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (16, 'layer-4', 'theramatic', NULL, 2);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (17, 'layer-4', 'magnamatic', NULL, 3);
INSERT OR IGNORE INTO product_layer_items (id, layer_id, product_id, subgroup_label, sort_order) VALUES (18, 'layer-4', 'spacematic', NULL, 4);

-- salespeople
INSERT OR IGNORE INTO salespeople (id, dealer_id, name, active) VALUES ('sp-amit', 'dlr-sharma', 'Amit', 1);
INSERT OR IGNORE INTO salespeople (id, dealer_id, name, active) VALUES ('sp-rahul', 'dlr-sharma', 'Rahul', 1);
INSERT OR IGNORE INTO salespeople (id, dealer_id, name, active) VALUES ('sp-sameer', 'dlr-sharma', 'Sameer', 1);
INSERT OR IGNORE INTO salespeople (id, dealer_id, name, active) VALUES ('sp-priya', 'dlr-sharma', 'Priya', 1);

-- price_campaigns
INSERT OR IGNORE INTO price_campaigns (id, name, product_id, discount_percent, start_at, end_at, description, terms, badge_label, status, deleted_at, created_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('motw-latexo-aug', 'Mattress of the Week', 'latexo', 5, '2026-08-11T00:00:00+05:30', '2026-08-27T23:59:59+05:30', 'Get an extra 5% off on Latexo — our natural latex mattress with premium bounce and breathability.', 'Valid on standard dealer orders during the campaign period. Cannot be combined with other offers.', 'Extra 5% OFF', 'active', NULL, '2026-08-21 05:27:48', 1, 0);

-- sell_campaigns
INSERT OR IGNORE INTO sell_campaigns (id, title, emoji, goal_text, reward_text, target_count, done_count, starts_at, ends_at, status, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('monsoon', 'MONSOON MATTRESS BONANZA', '🌧️', 'Sell 20 Orthomatic Mattresses', '5,000 Bonus Points', 20, 12, '2026-07-31T18:30:00.000Z', '2026-09-29T18:30:00.000Z', 'active', NULL, 1, 0);
INSERT OR IGNORE INTO sell_campaigns (id, title, emoji, goal_text, reward_text, target_count, done_count, starts_at, ends_at, status, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('sell-more', 'SELL MORE. EARN MORE.', '🔥', 'Sell 10 more Delight Mattresses', '1,500 Bonus Points', 10, 6, '2026-07-31T18:30:00.000Z', '2026-09-14T18:30:00.000Z', 'active', NULL, 1, 0);
INSERT OR IGNORE INTO sell_campaigns (id, title, emoji, goal_text, reward_text, target_count, done_count, starts_at, ends_at, status, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('pillow-push', 'PILLOW POWER WEEK', '☁️', 'Sell 50 Memory King Pillows', '2,000 Bonus Points', 50, 38, '2026-08-19T18:30:00.000Z', '2026-08-26T18:30:00.000Z', 'upcoming', NULL, 1, 0);
INSERT OR IGNORE INTO sell_campaigns (id, title, emoji, goal_text, reward_text, target_count, done_count, starts_at, ends_at, status, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('summer-clearance', 'SUMMER CLEARANCE', '☀️', 'Sell 15 Delight Cool Mattresses', '3,000 Bonus Points', 15, 15, '2026-05-31T18:30:00.000Z', '2026-07-30T18:30:00.000Z', 'expired', NULL, 1, 0);
INSERT OR IGNORE INTO sell_campaigns (id, title, emoji, goal_text, reward_text, target_count, done_count, starts_at, ends_at, status, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('festive-prebook', 'FESTIVE PRE-BOOK', '🎁', 'Pre-book 25 Spacematic Mattresses', 'Early bird pricing', 25, 0, '2026-08-31T18:30:00.000Z', '2026-10-14T18:30:00.000Z', 'upcoming', NULL, 1, 0);

-- distributor_campaigns
INSERT OR IGNORE INTO distributor_campaigns (id, distributor_id, name, product_name, discount_label, description, start_date, end_date, status, banner_emoji, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('camp-motw', 'dist-nagpur-01', 'Mattress of the Week', 'Latexo', 'Extra 5% OFF', 'Get an extra 5% off on Latexo — natural latex comfort for premium sleep.', '11 Aug 2026', '27 Aug 2026', 'active', '🔥', NULL, 1, 0);
INSERT OR IGNORE INTO distributor_campaigns (id, distributor_id, name, product_name, discount_label, description, start_date, end_date, status, banner_emoji, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('camp-monsoon', 'dist-nagpur-01', 'Monsoon Mattress Bonanza', 'Orthomatic', '5,000 Bonus Points', 'Sell 20 Orthomatic mattresses and earn 5,000 bonus reward points.', '01 Aug 2026', '30 Sep 2026', 'active', '🌧️', NULL, 1, 0);
INSERT OR IGNORE INTO distributor_campaigns (id, distributor_id, name, product_name, discount_label, description, start_date, end_date, status, banner_emoji, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('camp-pillow', 'dist-nagpur-01', 'Pillow Power Week', 'Memory King Pillow', '2,000 Bonus Points', 'Push Memory King pillows this week for extra dealer rewards.', '20 Aug 2026', '27 Aug 2026', 'upcoming', '☁️', NULL, 1, 0);
INSERT OR IGNORE INTO distributor_campaigns (id, distributor_id, name, product_name, discount_label, description, start_date, end_date, status, banner_emoji, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('camp-delight', 'dist-nagpur-01', 'Delight Summer Sale', 'Delight Cool', '3% Dealer Discount', 'Summer clearance on Delight Cool range.', '01 Jun 2026', '31 Jul 2026', 'expired', '☀️', NULL, 1, 0);
INSERT OR IGNORE INTO distributor_campaigns (id, distributor_id, name, product_name, discount_label, description, start_date, end_date, status, banner_emoji, deleted_at, whatsapp_target_dealers, whatsapp_target_distributors) VALUES ('camp-festive', 'dist-nagpur-01', 'Festive Pre-Book', 'Spacematic', 'Early bird pricing', 'Pre-book Spacematic for festive season deliveries.', '01 Sep 2026', '15 Oct 2026', 'upcoming', '🎁', NULL, 1, 0);

-- reward_catalog
INSERT OR IGNORE INTO reward_catalog (id, name, emoji, points_required, active, deleted_at) VALUES ('speaker', 'Bluetooth Speaker', '🎁', 3000, 1, NULL);
INSERT OR IGNORE INTO reward_catalog (id, name, emoji, points_required, active, deleted_at) VALUES ('backpack', 'BackRest Backpack', '🎒', 5000, 1, NULL);
INSERT OR IGNORE INTO reward_catalog (id, name, emoji, points_required, active, deleted_at) VALUES ('earbuds', 'Wireless Earbuds', '🎧', 8000, 1, NULL);
INSERT OR IGNORE INTO reward_catalog (id, name, emoji, points_required, active, deleted_at) VALUES ('watch', 'Smart Watch', '⌚', 12000, 1, NULL);

-- points_ledger
INSERT OR IGNORE INTO points_ledger (id, dealer_id, delta, balance_after, label, reference_type, reference_id, occurred_at) VALUES ('pl-init', 'dlr-sharma', 24500, 24500, 'Opening balance', NULL, NULL, '2026-08-21T05:27:48.940Z');

-- reward_claims
INSERT OR IGNORE INTO reward_claims (id, dealer_id, reward_catalog_id, name, emoji, points_spent, status, claimed_at, delivered_at) VALUES ('rw-sharma-1', 'dlr-sharma', NULL, 'Bluetooth Speaker', '🎁', 3000, 'delivered', '10 Aug 2026', '14 Aug 2026');
INSERT OR IGNORE INTO reward_claims (id, dealer_id, reward_catalog_id, name, emoji, points_spent, status, claimed_at, delivered_at) VALUES ('rw-sharma-2', 'dlr-sharma', NULL, 'BackRest Backpack', '🎒', 5000, 'pending', '28 Jul 2026', NULL);

-- orders
INSERT OR IGNORE INTO orders (id, dealer_id, distributor_id, placed_by_user_id, salesperson_id, status, placed_at, approved_at, rejected_at, rejection_reason, customer_name, customer_phone, customer_address, customer_email, total_items, total_value, notes, deleted_at, created_at, updated_at, delivered_at, rewards_credited_at) VALUES ('BR-10245', 'dlr-patil', 'dist-nagpur-01', 'user-dealer-sharma', NULL, 'order_placed', '2026-08-21T05:27:48.979Z', NULL, NULL, NULL, 'Amit Joshi', NULL, NULL, NULL, 2, 52400, NULL, NULL, '2026-08-21 05:27:48', '2026-08-21 05:27:48', NULL, NULL);
INSERT OR IGNORE INTO orders (id, dealer_id, distributor_id, placed_by_user_id, salesperson_id, status, placed_at, approved_at, rejected_at, rejection_reason, customer_name, customer_phone, customer_address, customer_email, total_items, total_value, notes, deleted_at, created_at, updated_at, delivered_at, rewards_credited_at) VALUES ('BR-10244', 'dlr-desai', 'dist-nagpur-01', 'user-dealer-sharma', NULL, 'order_placed', '2026-08-21T05:27:49.140Z', NULL, NULL, NULL, 'Priya Shah', NULL, NULL, NULL, 3, 67800, NULL, NULL, '2026-08-21 05:27:49', '2026-08-21 05:27:49', NULL, NULL);
INSERT OR IGNORE INTO orders (id, dealer_id, distributor_id, placed_by_user_id, salesperson_id, status, placed_at, approved_at, rejected_at, rejection_reason, customer_name, customer_phone, customer_address, customer_email, total_items, total_value, notes, deleted_at, created_at, updated_at, delivered_at, rewards_credited_at) VALUES ('BR-10243', 'dlr-sharma', 'dist-nagpur-01', 'user-dealer-sharma', NULL, 'order_placed', '2026-08-21T05:27:49.196Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 30200, NULL, NULL, '2026-08-21 05:27:49', '2026-08-21 05:27:49', NULL, NULL);
INSERT OR IGNORE INTO orders (id, dealer_id, distributor_id, placed_by_user_id, salesperson_id, status, placed_at, approved_at, rejected_at, rejection_reason, customer_name, customer_phone, customer_address, customer_email, total_items, total_value, notes, deleted_at, created_at, updated_at, delivered_at, rewards_credited_at) VALUES ('BR-10242', 'dlr-kulkarni', 'dist-nagpur-01', 'user-dealer-sharma', NULL, 'order_placed', '2026-08-21T05:27:49.266Z', NULL, NULL, NULL, 'Rahul Kadam', NULL, NULL, NULL, 1, 18700, NULL, NULL, '2026-08-21 05:27:49', '2026-08-21 05:27:49', NULL, NULL);
INSERT OR IGNORE INTO orders (id, dealer_id, distributor_id, placed_by_user_id, salesperson_id, status, placed_at, approved_at, rejected_at, rejection_reason, customer_name, customer_phone, customer_address, customer_email, total_items, total_value, notes, deleted_at, created_at, updated_at, delivered_at, rewards_credited_at) VALUES ('BR-10241', 'dlr-singh', 'dist-nagpur-01', 'user-dealer-sharma', NULL, 'order_placed', '2026-08-21T05:27:49.315Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 24600, NULL, NULL, '2026-08-21 05:27:49', '2026-08-21 05:27:49', NULL, NULL);
INSERT OR IGNORE INTO orders (id, dealer_id, distributor_id, placed_by_user_id, salesperson_id, status, placed_at, approved_at, rejected_at, rejection_reason, customer_name, customer_phone, customer_address, customer_email, total_items, total_value, notes, deleted_at, created_at, updated_at, delivered_at, rewards_credited_at) VALUES ('BR-10240', 'dlr-chavan', 'dist-nagpur-01', 'user-dealer-sharma', NULL, 'order_placed', '2026-08-21T05:27:49.371Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 15100, NULL, NULL, '2026-08-21 05:27:49', '2026-08-21 05:27:49', NULL, NULL);
INSERT OR IGNORE INTO orders (id, dealer_id, distributor_id, placed_by_user_id, salesperson_id, status, placed_at, approved_at, rejected_at, rejection_reason, customer_name, customer_phone, customer_address, customer_email, total_items, total_value, notes, deleted_at, created_at, updated_at, delivered_at, rewards_credited_at) VALUES ('BR-10238', 'dlr-menon', 'dist-nagpur-01', 'user-dealer-sharma', NULL, 'order_placed', '2026-08-21T05:27:49.424Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 12500, NULL, NULL, '2026-08-21 05:27:49', '2026-08-21 05:27:49', NULL, NULL);
INSERT OR IGNORE INTO orders (id, dealer_id, distributor_id, placed_by_user_id, salesperson_id, status, placed_at, approved_at, rejected_at, rejection_reason, customer_name, customer_phone, customer_address, customer_email, total_items, total_value, notes, deleted_at, created_at, updated_at, delivered_at, rewards_credited_at) VALUES ('BR-10235', 'dlr-patil', 'dist-nagpur-01', 'user-dealer-sharma', NULL, 'approved', '2026-08-21T05:27:49.480Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 15100, NULL, NULL, '2026-08-21 05:27:49', '2026-08-21 05:27:49', NULL, NULL);

-- order_items
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10245-Latexo', 'BR-10245', 'latexo', 'Latexo', '78 × 60', NULL, '6"', 1, 0, NULL, NULL, 18600, 11875, NULL, 11875, NULL, '2 × Fiber Pillows', 86, 11875, NULL);
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10245-Delight Cool', 'BR-10245', 'delight-cool', 'Delight Cool', '72 × 48', NULL, '8"', 1, 0, NULL, NULL, 16400, 11000, NULL, NULL, NULL, '2 × Fiber Pillows', 73, 11000, NULL);
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10244-Orthomatic', 'BR-10244', 'orthomatic', 'Orthomatic', '75 × 60', NULL, '8"', 2, 0, NULL, NULL, 22400, 15100, NULL, NULL, NULL, '2 × Fiber Pillows', 101, 30200, NULL);
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10244-Memory King Pillow', 'BR-10244', 'memory-king-pillow', 'Memory King Pillow', '17 × 27', NULL, '—', 4, 0, NULL, NULL, 1400, 950, NULL, NULL, NULL, '2 × Fiber Pillows', 6, 3800, NULL);
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10243-Orthomatic', 'BR-10243', 'orthomatic', 'Orthomatic', '78 × 60', NULL, '6"', 2, 0, NULL, NULL, 22400, 15100, NULL, NULL, NULL, '2 × Fiber Pillows', 101, 30200, NULL);
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10242-Latexo', 'BR-10242', 'latexo', 'Latexo', '72 × 66', NULL, '8"', 1, 0, NULL, NULL, 18600, 11875, NULL, 11875, NULL, '2 × Fiber Pillows', 79, 11875, NULL);
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10241-Twin Plush', 'BR-10241', 'twin-plush', 'Twin Plush', '72 × 36', NULL, '6"', 2, 0, NULL, NULL, 8600, 5800, NULL, NULL, NULL, '2 × Fiber Pillows', 39, 11600, NULL);
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10240-AquaFresh Plush', 'BR-10240', 'aquafresh-plush', 'AquaFresh Plush', '75 × 60', NULL, '6"', 1, 0, NULL, NULL, 12100, 8100, NULL, NULL, NULL, '2 × Fiber Pillows', 54, 8100, NULL);
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10238-Latexo', 'BR-10238', 'latexo', 'Latexo', '78 × 60', NULL, '6"', 1, 0, NULL, NULL, 18600, 11875, NULL, 11875, NULL, '2 × Fiber Pillows', 79, 11875, NULL);
INSERT OR IGNORE INTO order_items (id, order_id, product_id, product_name, size_requested, size_standard, thickness, quantity, perma, perma_corners, perma_notes, mrp, dealer_price, campaign_id, campaign_price, discount_percent, free_items, points_earned, line_total, notes) VALUES ('oi-BR-10235-Orthomatic', 'BR-10235', 'orthomatic', 'Orthomatic', '78 × 60', NULL, '6"', 1, 0, NULL, NULL, 22400, 15100, NULL, NULL, NULL, '2 × Fiber Pillows', 101, 15100, NULL);

-- order_timeline_events
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10245-Order Placed', 'BR-10245', 'Order Placed', '2026-08-21T05:27:48.979Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10245-Pending Distributor Approval', 'BR-10245', 'Pending Distributor Approval', '2026-08-21T05:27:48.979Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10244-Order Placed', 'BR-10244', 'Order Placed', '2026-08-21T05:27:49.140Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10244-Pending Distributor Approval', 'BR-10244', 'Pending Distributor Approval', '2026-08-21T05:27:49.140Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10243-Order Placed', 'BR-10243', 'Order Placed', '2026-08-21T05:27:49.196Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10243-Pending Distributor Approval', 'BR-10243', 'Pending Distributor Approval', '2026-08-21T05:27:49.196Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10242-Order Placed', 'BR-10242', 'Order Placed', '2026-08-21T05:27:49.266Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10242-Pending Distributor Approval', 'BR-10242', 'Pending Distributor Approval', '2026-08-21T05:27:49.266Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10241-Order Placed', 'BR-10241', 'Order Placed', '2026-08-21T05:27:49.315Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10241-Pending Distributor Approval', 'BR-10241', 'Pending Distributor Approval', '2026-08-21T05:27:49.315Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10240-Order Placed', 'BR-10240', 'Order Placed', '2026-08-21T05:27:49.371Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10240-Pending Distributor Approval', 'BR-10240', 'Pending Distributor Approval', '2026-08-21T05:27:49.371Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10238-Order Placed', 'BR-10238', 'Order Placed', '2026-08-21T05:27:49.424Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10238-Pending Distributor Approval', 'BR-10238', 'Pending Distributor Approval', '2026-08-21T05:27:49.424Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10235-Order Placed', 'BR-10235', 'Order Placed', '2026-08-21T05:27:49.480Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10235-Pending Distributor Approval', 'BR-10235', 'Pending Distributor Approval', '2026-08-21T05:27:49.480Z', NULL, NULL, NULL);
INSERT OR IGNORE INTO order_timeline_events (id, order_id, label, occurred_at, note, actor_user_id, status_key) VALUES ('te-BR-10235-Approved', 'BR-10235', 'Approved', '2026-08-21T05:27:49.480Z', NULL, NULL, NULL);

-- complaints
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10245', 'BR-10245', 'dlr-patil', 'dist-nagpur-01', 'Product defect', 'Mattress has a slight sag on one side after delivery.', 'in_progress', 0, '14 Aug 2026', '16 Aug 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10238', 'BR-10243', 'dlr-sharma', 'dist-nagpur-01', 'Delivery', 'Delivery was delayed by 4 days beyond promised date.', 'pending', 0, '12 Aug 2026', '12 Aug 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10231', 'BR-10242', 'dlr-kulkarni', 'dist-nagpur-01', 'Wrong item', 'Received 72×48 instead of ordered 75×60.', 'resolved', 0, '08 Aug 2026', '11 Aug 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10222', 'BR-0972', 'dlr-reddy', 'dist-nagpur-01', 'Packaging', 'Outer cover torn during transit.', 'pending', 0, '05 Aug 2026', '05 Aug 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10218', 'BR-0960', 'dlr-gupta', 'dist-nagpur-01', 'Product defect', 'Spring noise reported by customer after one week.', 'in_progress', 0, '02 Aug 2026', '10 Aug 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10210', 'BR-0948', 'dlr-desai', 'dist-nagpur-01', 'Billing', 'Invoice amount does not match dealer price agreed.', 'rejected', 0, '28 Jul 2026', '30 Jul 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10205', 'BR-0935', 'dlr-chavan', 'dist-nagpur-01', 'Delivery', 'Customer refused delivery due to wrong floor access.', 'resolved', 0, '25 Jul 2026', '27 Jul 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10198', 'BR-0920', 'dlr-menon', 'dist-nagpur-01', 'Product defect', 'Pillow set missing from bundle.', 'pending', 0, '22 Jul 2026', '22 Jul 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10190', 'BR-0910', 'dlr-singh', 'dist-nagpur-01', 'Other', 'Customer wants exchange for different firmness.', 'in_progress', 0, '18 Jul 2026', '20 Jul 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10182', 'BR-0898', 'dlr-kulkarni', 'dist-nagpur-01', 'Product defect', 'Stitching issue on mattress corner.', 'resolved', 0, '15 Jul 2026', '17 Jul 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10175', 'BR-0885', 'dlr-reddy', 'dist-nagpur-01', 'Delivery', 'Partial delivery — one item still pending.', 'pending', 0, '10 Jul 2026', '10 Jul 2026', NULL);
INSERT OR IGNORE INTO complaints (id, order_id, dealer_id, distributor_id, category, description, status, step, created_at, updated_at, deleted_at) VALUES ('CMP-10168', 'BR-0870', 'dlr-sharma', 'dist-nagpur-01', 'Wrong item', 'Wrong thickness delivered — 8 inch instead of 6 inch.', 'in_progress', 0, '05 Jul 2026', '08 Jul 2026', NULL);

-- system_settings
INSERT OR IGNORE INTO system_settings (key, value, updated_at) VALUES ('pending_reminder_hours', '2', '2026-08-21 05:27:49');

PRAGMA foreign_keys = ON;